Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 22
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	Ball_Gown
	1	all
	2

[Mon Aug 12 13:31:19 2019]
rule Ball_Gown:
    input: Sample_70160/Sample_70160_onlyKnown.gtf, Sample_70161/Sample_70161_onlyKnown.gtf, Sample_70162/Sample_70162_onlyKnown.gtf, Sample_70166/Sample_70166_onlyKnown.gtf, Sample_70167/Sample_70167_onlyKnown.gtf, Sample_70168/Sample_70168_onlyKnown.gtf, Sample_70169/Sample_70169_onlyKnown.gtf, Sample_70170/Sample_70170_onlyKnown.gtf, Sample_70171/Sample_70171_onlyKnown.gtf
    output: BallGown/gene_expression_table.txt, BallGown/transcript_fpkm.txt, BallGown/transcript_cov.txt, BallGown/whole_tx_table.txt, BallGown/filt_gene_expression_table.txt, BallGown/filt_transcript_fpkm.txt, BallGown/filt_transcript_cov.txt, BallGown/filt_whole_tx_table.txt
    jobid: 23

[Mon Aug 12 13:31:19 2019]
Error in rule Ball_Gown:
    jobid: 23
    output: BallGown/gene_expression_table.txt, BallGown/transcript_fpkm.txt, BallGown/transcript_cov.txt, BallGown/whole_tx_table.txt, BallGown/filt_gene_expression_table.txt, BallGown/filt_transcript_fpkm.txt, BallGown/filt_transcript_cov.txt, BallGown/filt_whole_tx_table.txt

RuleException:
CalledProcessError in line 14 of /home/manninm/pyflow-RNAseq/rules/BallGown.smk:
Command 'set -eo pipefail; echo BEGIN at $(date);  Rscript ../scripts/BallGown.R ; exitstat=$?; echo END at $(date); echo exit status was $exitstat; exit $exitstat' returned non-zero exit status 2.
  File "/home/manninm/pyflow-RNAseq/rules/BallGown.smk", line 14, in __rule_Ball_Gown
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/manninm/pyflow-RNAseq/.snakemake/log/2019-08-12T133119.443637.snakemake.log
