Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 22
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	3	HtSeq_Count
	1	HtSeq_Matrix
	3	HtSeq_Move
	1	all
	8

[Fri Aug  9 11:49:50 2019]
Job 21: htseq-count Sample_70161/Sample_70161Aligned.sortedByCoord.out.bam : 1 threads


[Fri Aug  9 11:49:50 2019]
Job 20: htseq-count Sample_70160/Sample_70160Aligned.sortedByCoord.out.bam : 1 threads


[Fri Aug  9 11:49:50 2019]
Job 22: htseq-count Sample_70162/Sample_70162Aligned.sortedByCoord.out.bam : 1 threads

[Fri Aug  9 11:49:50 2019]
Error in rule HtSeq_Count:
    jobid: 21
    output: Sample_70161/Sample_70161_htseq.cnt

RuleException:
CalledProcessError in line 9 of /home/manninm/pyflow-RNAseq/rules/HtSeq.smk:
Command 'set -eo pipefail; echo BEGIN at $(date);  htseq-count -f bam --stranded= no --idattr gene_id --order pos -m union Sample_70161/Sample_70161Aligned.sortedByCoord.out.bam /home/deepSeq/ENSEMBL_GRCH38/transcripts/Homo_sapiens.GRCh38.86.gtf > Sample_70161/Sample_70161_htseq.cnt ; exitstat=$?; echo END at $(date); echo exit status was $exitstat; exit $exitstat' returned non-zero exit status 2.
  File "/home/manninm/pyflow-RNAseq/rules/HtSeq.smk", line 9, in __rule_HtSeq_Count
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job HtSeq_Count since they might be corrupted:
Sample_70161/Sample_70161_htseq.cnt
[Fri Aug  9 11:49:50 2019]
Error in rule HtSeq_Count:
    jobid: 20
    output: Sample_70160/Sample_70160_htseq.cnt

RuleException:
CalledProcessError in line 9 of /home/manninm/pyflow-RNAseq/rules/HtSeq.smk:
Command 'set -eo pipefail; echo BEGIN at $(date);  htseq-count -f bam --stranded= no --idattr gene_id --order pos -m union Sample_70160/Sample_70160Aligned.sortedByCoord.out.bam /home/deepSeq/ENSEMBL_GRCH38/transcripts/Homo_sapiens.GRCh38.86.gtf > Sample_70160/Sample_70160_htseq.cnt ; exitstat=$?; echo END at $(date); echo exit status was $exitstat; exit $exitstat' returned non-zero exit status 2.
  File "/home/manninm/pyflow-RNAseq/rules/HtSeq.smk", line 9, in __rule_HtSeq_Count
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job HtSeq_Count since they might be corrupted:
Sample_70160/Sample_70160_htseq.cnt
[Fri Aug  9 11:49:50 2019]
Error in rule HtSeq_Count:
    jobid: 22
    output: Sample_70162/Sample_70162_htseq.cnt

RuleException:
CalledProcessError in line 9 of /home/manninm/pyflow-RNAseq/rules/HtSeq.smk:
Command 'set -eo pipefail; echo BEGIN at $(date);  htseq-count -f bam --stranded= no --idattr gene_id --order pos -m union Sample_70162/Sample_70162Aligned.sortedByCoord.out.bam /home/deepSeq/ENSEMBL_GRCH38/transcripts/Homo_sapiens.GRCh38.86.gtf > Sample_70162/Sample_70162_htseq.cnt ; exitstat=$?; echo END at $(date); echo exit status was $exitstat; exit $exitstat' returned non-zero exit status 2.
  File "/home/manninm/pyflow-RNAseq/rules/HtSeq.smk", line 9, in __rule_HtSeq_Count
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job HtSeq_Count since they might be corrupted:
Sample_70162/Sample_70162_htseq.cnt
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/manninm/pyflow-RNAseq/.snakemake/log/2019-08-09T114950.410113.snakemake.log
